"""create appointments table

Revision ID: 1c1accd8ff16
Revises: b587050c7429
Create Date: 2026-09-04 21:39:46.181529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1accd8ff16'
down_revision: Union[str, Sequence[str], None] = 'b587050c7429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'booked'::character varying"),
               existing_nullable=False)
    op.alter_column('appointments', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'Low'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
