"""initial schema

Revision ID: 449bebcc3d92
Revises: 570f764184a6
Create Date: 2026-08-16 14:51:27.581791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '449bebcc3d92'
down_revision: Union[str, Sequence[str], None] = '570f764184a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultations', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('consultations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_consultations_user_id'), 'consultations', ['user_id'], unique=False)
    op.alter_column('users', 'village',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'village',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_consultations_user_id'), table_name='consultations')
    op.alter_column('consultations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('consultations', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
