"""Add Gemini analysis fields

Revision ID: 4f9ac70c5212
Revises: d5474bb0d845
Create Date: 2026-08-09 10:54:53.920611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9ac70c5212'
down_revision: Union[str, Sequence[str], None] = 'd5474bb0d845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('possible_conditions', sa.Text(), nullable=True))
    op.add_column('consultations', sa.Column('recommended_tests', sa.Text(), nullable=True))
    op.add_column('consultations', sa.Column('red_flags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'red_flags')
    op.drop_column('consultations', 'recommended_tests')
    op.drop_column('consultations', 'possible_conditions')
    # ### end Alembic commands ###
