"""Add doctor notes

Revision ID: d5474bb0d845
Revises: 7c39690ca839
Create Date: 2026-08-07 23:03:57.962616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5474bb0d845'
down_revision: Union[str, Sequence[str], None] = '7c39690ca839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('doctor_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'doctor_notes')
    # ### end Alembic commands ###
